### ISSUE TITLE
Support Python 3 / NumPy 1.12

### ISSUE THREAD

**Issue by tsmithe** [coin-or/rbfopt#10]
Hello,

I have been playing with rbfopt using recent Python and NumPy versions, and have attached a patch with a couple of suggested changes that make the tests usable (though by default the tests do not seem to find the optima; I do not know if that is a different bug, or expected, or somehow the result of using Python 3...). I would like to implore you to support recent versions of the software in this ecosystem: Python 3 is a very nice upgrade over 2.7, and time isn't going backwards!

[rbfopt-py3-patch.txt](https://github.com/coin-or/rbfopt/files/1061753/rbfopt-py3-patch.txt)

All the best, and thanks for the great software.

**Comment by gnannicini** [comment]
Hi Toby,
thanks for the patch.
The development branch on github supports Python 3. There are also numerous
performance improvements and I am in the phase of testing to choose the
best default settings.
I didn't push development to master yet because I tend to be cautious with
that, but I will make a release candidate soon. Notice that this would be a
major version update and it is (slightly) backward incompatible.

Giacomo

**Comment by tsmithe** [comment]
Hi Giacomo,

Many thanks for the quick response. I look forward to the new release and all those to follow! In the meantime, I will devote myself to understanding rbfopt's algorithms.

Cheers,

Toby

**Comment by gnannicini** [comment]
All tests were passed, I updated the master with version 3. Lots of updates. I will make a new packaged release soon.

**Comment by tsmithe** [comment]
Wonderful, thanks!
