### ISSUE TITLE
ImportError: Import by filename is not supported.

### ISSUE THREAD

**Issue by TuanNguyen27** [coin-or/rbfopt#11]
Traceback (most recent call last):
  File "src/rbfopt_cl_interface.py", line 211, in <module>
    bb = importlib.import_module(args.black_box_module)
  File "/Users/tuan.nguyen/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
  __ import __(name)
ImportError: Import by filename is not supported.

I'm using Python 2.7.13 |Anaconda 4.4.0 (x86_64)|, is there something wrong with my setup?

**Comment by gnannicini** [comment]
Hi Tuan,
what is the command line you are using? Be careful that you can only give a
module *name*, not the full path.
E.g. you can write
python3 rbfopt_cl_interface -m module_name
but you cannot write
python3 rbfopt_cl_interface -m path/to/module_name

Let me know if this is the issue; otherwise, it'd be great if you could
provide more context.

Thanks

G

**Comment by TuanNguyen27** [comment]
Hi! The command i am using is 
python src/rbfopt_cl_interface.py -m src/rbfopt_black_box_example.py

**Comment by gnannicini** [comment]
Hi Tuan,
the -m option requires the module name, not the path:

python src/rbfopt_cl_interface.py -m rbfopt_black_box_example

Of course the module should be a in a folder that can be accessed by Python.

Giacomo
