### ISSUE TITLE
Silencing printed output

### ISSUE THREAD

**Issue by kevinsung** [coin-or/rbfopt#14]
When I run an optimization, a bunch of stuff gets printed out, e.g.
```
...
Iter   0 Initialization : obj~        -0.889346 time    3.26 gap   100.00  
Iter   0 Initialization : obj~        -0.952863 time    3.26 gap   100.00  
Iter   0 Initialization : obj~        -0.964704 time    3.26 gap   100.00  
Iter   0 Initialization : obj~        -0.902433 time    3.26 gap   100.00  
Iter   0 Initialization : obj~        -0.973815 time    3.26 gap   100.00  
Iter   0 Initialization : obj~        -0.832574 time    3.26 gap   100.00  
...
```
Is there an option to silence this?

**Comment by gnannicini** [comment]
Kevin:
With the command-line you can use the --log option to direct to a file (or
/dev/null).
With the API, the RbfoptAlgorithm class has a function
set_output_stream(stream). You can give it any valid stream that has
"write" and "flush" functions, including os.devnull. That should silence
any output.

Cheers

Giacomo

**Comment by kevinsung** [comment]
Cool. I was looking for a "verbose" option in settings, but this works too. Thanks!

**Comment by kevinsung** [comment]
Okay I tried that and it silenced most of the output, but I'm still getting stuff like
```
WARNING: Loading a SolverResults object with a warning status into
    model=unknown;
        message from solver=Ipopt 3.12.8\x3a Maximum Number of Iterations
        Exceeded.
```
Shouldn't that be directed to the output stream as well?

**Comment by gnannicini** [comment]
Kevin,
that message comes from Pyomo (one of the libraries used by RBFOpt) and I
am not sure how to redirect it. I've never been able to suppress the error
messages from Pyomo. You can leave the issue open, I will try to find a fix.

**Comment by gnannicini** [comment]
Kevin,
should be fixed in the latest master branch. There is an option "debug" in RbfoptSettings, set to False by default, that disables most error and warning messages from RBFOpt and from Pyomo.

However, the particular message that you posted above is *hardcoded* in older version of Pyomo, and I cannot suppress it. This was a bug that has been fixed a few months ago.

You should no longer see those messages (and similar messages) if you have a recent Pyomo and use the latest RBFOpt master.
