### ISSUE TITLE
Is there a way to skip an output value?

### ISSUE THREAD

**Issue by TheoChristiaanse** [coin-or/rbfopt#28]
I've been playing around with the following scenario:

```
import rbfopt
import numpy as np
def obj_funct(x):
    sol=x[0]*x[1] - x[2]
    #print(type(sol))
    #print(sol)
    check = (np.greater(np.mod(sol,20),19))
    #print(check)
    
    if check:
        val= None
    else:
        val= sol
    #print(val)
    return val
    
    
bb = rbfopt.RbfoptUserBlackBox(3, np.array([0] * 3), np.array([10] * 3),np.array(['R', 'I', 'R']), obj_funct_noisy=obj_funct)

settings = rbfopt.RbfoptSettings(max_evaluations=50)
alg = rbfopt.RbfoptAlgorithm(settings, bb)
val, x, itercount, evalcount, fast_evalcount = alg.optimize()
```

At some points my model will spit out a None value. Is there a way to make sure the optimizer ignores these spots in the solution space when we obtain this None value? There seems to be an automated clipping flag, but I'm unsure how this works.

**Comment by gnannicini** [comment]
No, at the moment invalid outputs are not supported. The algorithm will fail throwing some exception if you return None rather than a numerical value. 

One possible workaround is to return a large (but not *too* large) value instead of None. I.e., if you know that the objective function has range [0, 100], you could return 200 instead of None, so that the algorithm understands this is not a desirable point. Note that if you return a value which is too large, e.g., 1.0e30, it will degrade performance due toh the automatic rescaling done by the algorithm.

**Comment by TheoChristiaanse** [comment]
Thanks for the tip. I will use this option.

**Comment by vitalyisaev2** [comment]
I apologize for bumping an old issue, just curious if some proper method of notifying rbofpt about bad function value has been implemented since that? 

Normally it's quite hard to find out such a value (not *too large*, but not *too small*) without detailed exploration of the objective function.

Thank you!

**Comment by gnannicini** [comment]
No, it has not been implemented. It should be relatively easy to modify the
code so that a dynamic value is chosen at every iteration, to overwrite the
"bad" function values; this would help in the scenario you are describing.
It may be added in the future, if I have time or if some kind soul
contributes it.
