### ISSUE TITLE
The complexity of the rbfopt algorithm

### ISSUE THREAD

**Issue by wlxer** [coin-or/rbfopt#50]
Hi, I am recently using the library for a combinatorial optimization problem. The objective function is deterministic but non-differentiable and discontinuous, so I treated him as a black box. The original problem is NP-hard, and here I want to know the computational complexity of the algorithm using the RBFOPT solver since I don't see a description of the algorithm complexity in the relevant papers.

**Comment by gnannicini** [comment]
It's difficult to answer that question precisely. Black-box optimization given only an input oracle is clearly NP-hard. At best, an algorithm can guarantee an \epsilon-approximate solution in exponential time in the size of the domain and in 1/\epsilon, because *any* algorithm might have to explore the entire domain on a generic black-box problem. RBFOpt is no exception.
